<section>
    <div class="section">
        <div class="section-1">
            <div class="intro-wrapper">
                <div class="card">
                    <div class="content">
                        <h2>Seo Se Chan</h2>
                        <span></span>
                        <p>
                            안녕하세요. 제 이름은 <strong>서세찬</strong>입니다.</br>
                            스타트업에서 2년동안 <strong>PHP</strong>와 <strong>HTML/CSS JQUERY</strong>를
                            이용한 다양한 종류의 웹사이트 개발경험이 있으며, <br/>
                            개발 외에 <strong>운동</strong>과 <strong>독서</strong>를 좋아하는 개발자입니다.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="test">
    <div class="section">
        <div class="border-section">
            <h2>스킬</h2>
            <span></span>
            <p>Phalcon을 이용한 PHP를 주력으로 최근에는 HTML/CSS와 SCRIPT+JQUERY를 활용한 프론트 엔드 기술 연마중</p>
        </div>
        <div class="section-2">
            <div class="ssc-container">
                <div class="skill-row ssc-clearfix first">
                    <div class="item front-item category">
                        <span>FRONT-END</span>
                    </div>
                    <div class="item front-item html-css">
                        <span>HTML/CSS</span>
                    </div>
                    <div class="item front-item bootstrap">
                        <span>BOOTSTRAP</span>
                    </div>
                    <div class="item front-item js">
                        <span>JS</span>
                    </div>
                    <div class="item front-item jquery">
                        <span>JQUERY</span>
                    </div>
                </div>
                <div class="skill-row ssc-clearfix">
                    <div class="item back-item category">
                        <span>BACK-END</span>
                    </div>
                    <div class="item back-item">
                        <span>PHP</span>
                    </div>
                    <div class="item back-item">
                        <span>NODE JS</span>
                    </div>
                    <div class="item back-item">
                        <span>MYSQL</span>
                    </div>
                    <div class="item back-item">
                        <span>UBUNTU</span>
                    </div>
                </div>
                <div class="skill-row ssc-clearfix last">
                    <div class="item tool-item category">
                        <span>TOOLS</span>
                    </div>
                    <div class="item tool-item">
                        <span>PHALCON</span>
                    </div>
                    <div class="item tool-item">
                        <span>EXPRESS</span>
                    </div>
                    <div class="item tool-item">
                        <span>WORKBENCH</span>
                    </div>
                    <div class="item tool-item">
                        <span>GITHUB</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="section section-3">
        <div class="border-section">
            <h2>포트폴리오</h2>
            <span></span>
            <p>약 2년간 Phalcon PHP 프레임워크를 이용한 다양한 종류의 웹 사이트 개발</p>
        </div>
        <div class="ssc-row">
            <div class="ssc-item-3 item-start">
                <h3>최근에 작업목록</h3>
                <span></span>
                <p>
                    다양한 서비스의 기획에 직접 참여
                    <br/>
                    Front-end 및 Server 개발 총괄
                </p>
            </div>
            <div class="ssc-item-3 item tuttoroom">
                <div class="hover-bg">
                    <h3 class="title">튜토룸</h3>
                    <span class="line"></span>
                    <div class="desc">
                        <p>관계형 SNS 서비스</p>
                    </div>
                </div>
            </div>
            <div class="ssc-item-3 item bookk">
                <div class="hover-bg">
                    <h3 class="title">부크크</h3>
                    <span class="line"></span>
                    <div class="desc">
                        <p>도서 출판 및 판매 플랫폼</p>
                    </div>
                </div>
            </div>
            <div class="ssc-item-3 item laughingbeans">
                <div class="hover-bg">
                    <h3 class="title">래핑빈</h3>
                    <span class="line"></span>
                    <div class="desc">
                        <p>외국어 학습 플랫폼</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="ssc-row">
            <div class="ssc-item-3 item ipoptv">
                <div class="hover-bg">
                    <h3 class="title">아이팝티비</h3>
                    <span class="line"></span>
                    <div class="desc">
                        <p>댄스 중심의 문화 콘텐츠 웹 사이트</p>
                    </div>
                </div>
            </div>
            <div class="ssc-item-3 item moruwa">
                <div class="hover-bg">
                    <h3 class="title">모루와</h3>
                    <span class="line"></span>
                    <div class="desc">
                        <p>반지 제작 웹 사이트</p>
                    </div>
                </div>
            </div>
            <div class="ssc-item-3 item peoplefund">
                <div class="hover-bg">
                    <h3 class="title">피플펀드</h3>
                    <span class="line"></span>
                    <div class="desc">
                        <p>핀테크 대출/투자 플랫폼</p>
                    </div>
                </div>
            </div>
            <div class="ssc-item-3 item-end">
                <h3>더 많은 작업목록</h3>
                <span></span>
                <p>더 보러 가기</p>
            </div>
        </div>
    </div>
</section>
