<div class="tl-wrapper">
    <div class="tl-content">
        <div class="tl-header now">Now</div>
        <div class="tl-item tuttoroom">
            <div class="tl-icon">T</div>
            <div class="tl-body">
                <h3 class="title">Tuttoroom (끝을 모르는 프로젝트)</h3>
                <div class="tl-media">
                    <div class="tl-img"></div>
                </div>
                <div class="tl-desc">
                    <table>
                        <tbody>
                        <tr>
                            <td class="th">기간</td>
                            <td>2015년 3월 - 2015년 10월</td>
                        </tr>
                        <tr>
                            <td class="th">담당</td>
                            <td>서버(메인), 프론트엔드(메인)</td>
                        </tr>
                        <tr class="last">
                            <td class="th">한줄평</td>
                            <td>프로젝트는 시작보다 끝이 100배는 더 어렵다.</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="tl-item laughingbeans">
            <div class="tl-icon">L</div>
            <div class="tl-body">
                <h3 class="title">Laughingbeans</h3>
                <div class="tl-media">
                    <div class="tl-img"></div>
                </div>
                <div class="tl-desc">
                    <table>
                        <tbody>
                        <tr>
                            <td class="th">기간</td>
                            <td>2015년 6월 - 2016년 8월</td>
                        </tr>
                        <tr>
                            <td class="th">담당</td>
                            <td>서버(서브), 프론트엔드(서브)</td>
                        </tr>
                        <tr class="last">
                            <td class="th">한줄평</td>
                            <td>협업과 서브 스매시!</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="tl-item bookk">
            <div class="tl-icon">B</div>
            <div class="tl-body">
                <h3 class="title">Bookk</h3>
                <div class="tl-media">
                    <div class="tl-img"></div>
                </div>
                <div class="tl-desc">
                    <table>
                        <tbody>
                        <tr>
                            <td class="th">기간</td>
                            <td>2015년 9월 - 2016년 2월</td>
                        </tr>
                        <tr>
                            <td class="th">담당</td>
                            <td>서버(메인), 프론트엔드(메인)</td>
                        </tr>
                        <tr class="last">
                            <td class="th">한줄평</td>
                            <td>다양한 경험을 한 프로젝트</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="tl-item hooks">
            <div class="tl-icon">H</div>
            <div class="tl-body">
                <h3 class="title">The Hooks</h3>
                <div class="tl-media">
                    <div class="tl-img"></div>
                </div>
                <div class="tl-desc">
                    <table>
                        <tbody>
                        <tr>
                            <td class="th">기간</td>
                            <td>2015년 10월 - 2016년 12월</td>
                        </tr>
                        <tr>
                            <td class="th">담당</td>
                            <td>API 개발</td>
                        </tr>
                        <tr class="last">
                            <td class="th">한줄평</td>
                            <td>태그 기반 추천 알고리즘</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>