<div class="board-list">
    <div class="board-item">
        <div class="item-header">
            <h2>내 생각을 구체화 시킬수 있는 개발 공부</h2>
        </div>
        <div class="item-body">
            <div class="img-wrapper">
                <img src="assets/img/drawing.jpg" />
                <p>이미지에 대한 설명글을 입력하세요</p>
            </div>
            <p>개발은 내가 머릿 속에서 추상적으로 생각하는 것들을 구체화 하여 눈앞에서 생동감있게 움직일수 있도록 도와준다</p>
            <ul>
                <li></li>
                <li></li>
            </ul>
            <ol>
                <li></li>
                <li></li>
            </ol>
        </div>
        <div class="item-footer">
            footer
        </div>
    </div>
    <div class="board-item">
        <div class="item-header">
            <h2>내 생각을 구체화 시킬수 있는 개발 공부</h2>
        </div>
        <div class="item-body">
            <div class="img-wrapper">
                <img src="assets/img/drawing.jpg" />
                <p>이미지에 대한 설명글을 입력하세요</p>
            </div>
            <p>개발은 내가 머릿 속에서 추상적으로 생각하는 것들을 구체화 하여 눈앞에서 생동감있게 움직일수 있도록 도와준다</p>
            <ul>
                <li></li>
                <li></li>
            </ul>
            <ol>
                <li></li>
                <li></li>
            </ol>
        </div>
        <div class="item-footer">
            footer
        </div>
    </div>
</div>