<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>SSCHAN's Portfolio</title>
    <link rel="icon" type="image/png" href="/assets/img/favicon.ico">
<!--    <link rel="stylesheet" href="/assets/css/bootstrap.css">-->
    <link rel="stylesheet" href="/assets/css/normalize.css">
    <link rel="stylesheet" href="/assets/css/navbar.css">
    <link rel="stylesheet" href="/assets/css/default.css">
    <?php $this->assets->outputCss(); ?>
</head>
<body class="loading">
<div id="init-loading" class="loading">
    <div>
        <h1>SSCHAN</h1>
        <p>My nickname is <strong>sseba</strong></p>
        <img src="/assets/img/svg-loaders/puff.svg" />
    </div>
</div>
<?php echo $this->getContent(); ?>
<script src="/assets/js/jquery-2.1.4.js"></script>
<script src="/assets/js/bootstrap.js"></script>
<script src="/assets/js/default.js"></script>
<?php $this->assets->outputJs(); ?>
<div id="ssc-navbar-backdrop"></div>
</body>
</html>