<div class="board ssc-clearfix">
    <div id="board-sidebar">
        <div class="board-header">
            <h1 class="title">테마 블로그</h1>
            <p class="desc">테마 블로그를 제작중입니다.</p>
        </div>
        <form method="post" id="board-search">
            <div class="ssc-form-group">
                <label class="ssc-sr-only">검색</label>
                <input type="text" class="ssc-form-control" placeholder="검색..." />
            </div>
        </form>
        <div class="section">
            <h3 class="title">최근 게시글</h3>
            <ul>
                <li><a href="#">Recent posts 1</a></li>
                <li><a href="#">Recent posts 2</a></li>
                <li><a href="#">Recent posts 3</a></li>
                <li><a href="#">Recent posts 4</a></li>
                <li><a href="#">Recent posts 5</a></li>
            </ul>
        </div>
        <div class="section">
            <h3 class="title">카테고리</h3>
            <ul>
                <li><a href="#">개발자 습득 지식</a></li>
                <li><a href="#">세상 돌아가는 이야기</a></li>
                <li><a href="#">옷깃만 스쳐도 인연</a></li>
                <li><a href="#">행간의 미학</a></li>
                <li><a href="#">영상의 즐거움</a></li>
            </ul>
        </div>
    </div>
    <button type="button" class="ssc-btn board-sidebar-btn">
        <span class="light">열림</span>
    </button>
    <div id="board-body">
        <?php echo $this->getContent(); ?>
    </div>
</div>


