<?php
/**
 * @var $page_location string
 */
?>


<div class="ssc-navbar ssc-navbar-fixed-top">
    <div class="ssc-container">
        <button type="button" class="ssc-btn-sidebar">
            <span class="ssc-sr-only">Navigation toggle(네비게이션 토글)</span>
            <span class="ssc-sidebar-icon"></span>
            <span class="ssc-sidebar-icon"></span>
            <span class="ssc-sidebar-icon"></span>
            <span class="ssc-right-to"></span>
        </button>
        <div class="ssc-brand">
            <h1>SSCHAN</h1>
            <p>sschan's portfolio site</p>
        </div>
        <div class="menu ssc-pull-right">
            <ul class="ssc-clearfix">
                <li><a href="javascript:void(0)" class="intro-page active">소개</a></li>
                <li><a href="javascript:void(0)" class="skill-page">스킬</a></li>
                <li><a href="javascript:void(0)" class="portfolio-page">포트폴리오</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="main  <?php echo $page_location; ?>">
<?php echo $this->getContent() ; ?>
</div>
