<div class="ssc-navbar ssc-navbar-fixed-top">
    <div class="ssc-container">
        <button type="button" class="ssc-btn-sidebar">
            <span class="ssc-sr-only">Navigation toggle(네비게이션 토글)</span>
            <span class="ssc-sidebar-icon"></span>
            <span class="ssc-sidebar-icon"></span>
            <span class="ssc-sidebar-icon"></span>
        </button>
        <div class="ssc-brand">
            <h1>SSCHAN</h1>
            <p>sschan's portfolio site</p>
        </div>
        <div class="menu ssc-pull-right">
            <ul class="ssc-clearfix">
                <li><a href="">소개</a></li>
                <li><a href="">스킬</a></li>
                <li><a href="">포트폴리오</a></li>
                <li><a href="">연락처</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="main">
<?php echo $this->getContent() ; ?>
</div>
