<div class="ssc-carousel">
    <div class="ssc-carousel-wrapper">
        <div class="ssc-carousel-window">
            <div class="item">your content 1</div>
            <div class="item">your content 2</div>
            <div class="item">your content 3</div>
            <div class="item">your content 4</div>
        </div>
    </div>
    <div class="ssc-carousel-navigation ssc-clearfix">
        <button class="prev-btn ssc-pull-left"><< 이전</button>
        <button class="next-btn ssc-pull-right">다음 >></button>
    </div>
</div>

<div class="ssc-carousel">
    <div class="item">your content 1</div>
    <div class="item">your content 2</div>
    <div class="item">your content 3</div>
    <div class="item">your content 4</div>
</div>
